### PR TITLE
Add AxonIQ Playbook to start pages

### PR DESCRIPTION
**Pull request by BraininaBowl**

### CODE REVIEW

**Review by CodeDrivenMitch — APPROVED** [review]
LGTM

**Review by CodeDrivenMitch — CHANGES_REQUESTED** [review]
This will fail to merge:
```
build/site/reference-guide/index.html
 112:74  error  'AxonIQ Playbook' should use sentence-style capitalization.  AxonIQ.Headings 
```

**Comment by BraininaBowl** [comment]
> This will fail to merge:
> 
> ```
> build/site/reference-guide/index.html
>  112:74  error  'AxonIQ Playbook' should use sentence-style capitalization.  AxonIQ.Headings 
> ```

I added a PR to AxonIQ Vale to fix this: https://github.com/AxonIQ/axoniq-vale-package/pull/1

**Review by CodeDrivenMitch — APPROVED** [review]
:partying_face:

**Pull request merged**
