### PR TITLE
faq for Console

### PR DESCRIPTION
**Pull request by bruceaxoniq**

### CODE REVIEW

**Comment by bruceaxoniq** [comment]
@dgomezg  I'm trying to create the FAQ for the Console as a "Basics" document. I have not yet understood how everything works in Antora, so I'm getting the error stating that there is a duplicate "nav".

When you get the opportunity, can you let me know what I'm doing wrong?

**Comment by dgomezg** [comment]
@bruceaxoniq I've solved the issue. The problem was caused because the `antora.yml` descriptor in `axoniq-console-faq` had the same value for the `name:` property from the `axon-server-installation-guides` module. Thus, for antora, both modules were actually the same one, and that's why it was complaining about the duplicate `nav.adoc` files (because there were actually two navigation files configured for the same logical module.

The problem was probably caused by a Cmd+C/Cmd+V as the starting point for creating the new doc module, and then not changing the `name` property in the new descriptro.... Basically what I used to call "a problem caused by a CopyPasteException" ;)

I've changed the `name` property in `axoniq-console-faq/antora.yml` to `axoniq_console_faq` and now everything works.

**Comment by bruceaxoniq** [comment]
Thanks so much for the help!

**Comment by dgomezg** [comment]
Nevertheless, I still have a doubt, because I can't see where the FAQ is actually linked in axonIQ library.

But that probably involves the way that the index pages are built. Let me check into it.

**Review by dgomezg — COMMENTED** [review]
Now that the name in the antora.yml is fixed, it LGTM.

**Pull request merged**
