### PR TITLE
Removal of Contribution Guide package

### PR DESCRIPTION
**Pull request by SaraTorrey**
This PR will close issue #51

### CODE REVIEW

**Review by smcvb — APPROVED** [review]
Looks good to me :+1:

**Review by CodeDrivenMitch — APPROVED** [review]

**Comment by CodeDrivenMitch** [comment]
The build fails because there's still a reference: 
```[20:33:48.284] ERROR (asciidoctor): target of xref not found: contibution-guide::index.adoc
    file: /home/runner/work/axoniq-library-site/axoniq-library-site/content/home/modules/ROOT/nav.adoc
    source: /home/runner/work/axoniq-library-site/axoniq-library-site (branch: HEAD <worktree> | start path: content/home)
```

**Review by CodeDrivenMitch — CHANGES_REQUESTED** [review]
[20:33:48.284] ERROR (asciidoctor): target of xref not found: contibution-guide::index.adoc
    file: /home/runner/work/axoniq-library-site/axoniq-library-site/content/home/modules/ROOT/nav.adoc
    source: /home/runner/work/axoniq-library-site/axoniq-library-site (branch: HEAD <worktree> | start path: content/home)

**Comment by SaraTorrey** [comment]
@CodeDrivenMitch, I made the changes you requested. Please check again to see if there is anything else I need to change. Thanks.

**Comment by smcvb** [comment]
As the build succeeds right now, I am pretty confident your change fixed things, @SaraTorrey!

**Pull request merged**
